### ISSUE TITLE
Chrome Extension doesn't seem to contact server correctly

### ISSUE THREAD

**Issue by x4121** [cpoppema/pass-browser-chrome#1]
After unlocking I immediately get an "404: Server did not respond or timed out." message.
No matter if I specify a local (tried localhost, 127.0.0.1 and own IP) or remote server (tried url and IP), both with and without port specified.
The response comes so fast, that I'm not quite sure if the request is even sent.
Next thing is, I can't seem to find any trace of a request in my server logs.

Is there any way to start the extension and server with verbose output to try to debug this issue?

**Comment by cpoppema** [comment]
Thanks for taking an interest! @x4121 

I suspect you're missing a leading http:// or https://. Without it, an exception is thrown immediately in server.js when an XMLHttpRequest is created. Currently there is no validation to any input in the options screen, sorry for that.

> Is there any way to start the extension and server with verbose output to try to debug this issue?

Currently the server simply returns a JSON with an error message whenever an _expected_ error occurs and it may crash otherwise with a simple Node.js stacktrace if something unexpected happens, but that trace should still help you out (so far I've only seen this in case the password directory did not have proper permissions).

To debug the plugin you can look in three places for error log messages: either the content script, the popup or the background page throws an error.

Errors in the content script will show up in the javascript console (ctrl+shift+i)
Errors in the popup will show up in the console in the popup's window (rightclick the extension's icon and choose "Inspect pop" and keep a look out int that console.
Otherwise you'll need to enable "Developer mode" in ``chrome://extensions`` (right top corner), scroll down to the plugin and click on the then visible link ``background page``. Here you can also look at the "Network" tab to see requests to the server as well as any log messages.

In this case, if my assumption is correct you should see a message like this in the background page's javascript console:

```
XMLHttpRequest cannot load localhost:3000/secrets/. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

**Comment by x4121** [comment]
Thanks for the fast reply.
Prefixing the protocol solved the 404.
