### ISSUE TITLE
Chrome Extension fails to decrypt the response from server

### ISSUE THREAD

**Issue by x4121** [cpoppema/pass-browser-chrome#2]
On trying to fill, copy or show the password, the Extension outputs "400: Unknown error when decrypting received password".

The server lookup seems to work
```
auth-middleware.js: request body contained a public key with id "9174510F1607714E".
store.js: looking for key id "9174510F1607714E" and key id "1607714E".
...
store.js: comparing against "9174510F1607714E"..  is a match
```

I looked at the request end created one with my own public key, sent it via curl and could decrypt the output. So encryption/decryption does work.
Is there a way to retrieve the extension's private key so I can check if there's something wrong with that?

**Comment by x4121** [comment]
I took a closer look at the public key. In the extension it says something like
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js VERSION
Comment: http://openpgpjs.org

xsBNBFb/5boBCADEEF+orbmWQH09t8SwDtyIDq8zs37noirSX8s3dohl3MBO
...
```

If I do `echo "-----BEGIN PGP PUBLIC KEY..." | gpg --import -` and `gpg --armor --export $id` i get something like
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFb/5boBCADEEF+orbmWQH09t8SwDtyIDq8zs37noirSX8s3dohl3MBON7k4
...
```
So I'm not sure if there is going something wrong during the key import

**Comment by cpoppema** [comment]
I'm not entirely sure what is going wrong here, I don't think the public key difference matters. All my keys look different when I export them with ``gpg --export --armor <id>``, but they all work fine. Looks to me the key in the plugin and the key on the server have different metadata in the export along with the key. If I do a quick comparison using ``gpg --list-packets <keyfile>`` I see that the public key on my server contains an extra chunk with the signing information which makes sense because I had to sign that key before I could use it.

If you see the list of secrets in the plugin just fine, I don't think the problem lies with the private key, that list is also sent encrypted. The big difference is that the node server uses the public key used for authentication to encrypt the response so a mismatch between the private and public key is highly unlikely in this case. The encrypted part of the response per secret is not generated by the node server because the files on the filesystem are already encrypted. The server only wraps the file contents inside a PGP message. Can you check if there are any exceptions in the javascript console of the background page ?

To get the private key for debugging purposes you can run this javascript in either the console from the popup, background page or the global devtools (ctrl+shift+i) and change the scope from "top" to "pass-browser-chrome"

```javascript
chrome.storage.local.get(['privateKey'], function cb(items) {
  copy(items.privateKey);
});
```

After executing you can simply paste your key.

**Comment by cpoppema** [comment]
Here's a thought @x4121, did you perhaps went through the entire process again while maybe forgetting to sign the key ? Eventhough ``pass`` will throw a bunch of errors, the key id is still added to the ``.gpg-id`` file and so the node server thinks you have access. That way you can see the list, but are unable to copy/show/fill the password.

Or did you perhaps (while debugging) add your key id to the .gpg-id file manually after you ran ``pass init`` without the key from the plugin ? Run ``pass init $key1 $key2``, edit the file and add ``$key3``. In that case, the same applies. The plugin can show the list of secrets, but cannot copy/show/fill the password and shows the same message.

**Comment by x4121** [comment]
Another wild speculation. The list is encrypted via OpenPGP.js contain `\r\n`, while the keys are encrypted with GnuPG and just contain `\n` as line breaks. Maybe some regex doesn't see this as a valid pgp message?

Output of `/secrets/`:
```
-----BEGIN PGP MESSAGE-----\r\nVersion: OpenPGP.js v2.2.0\r\n...\r\n-----END PGP MESSAGE-----\r\n
```
Output of `/secret/`:
```
-----BEGIN PGP MESSAGE-----\n\n...\n-----END PGP MESSAGE-----
```

**Comment by x4121** [comment]
In the background page there is an error
```
background.js:18 TypeError: Cannot read property 'isDecrypted' of null
    at d.decrypt (background.js:18)
    at background.js:18
    at background.js:18
    at m (background.js:18)
    at Object.h [as decryptMessage] (background.js:18)
    at Object.callback (background.js:1)
    at safeCallbackApply (extensions::sendRequest:21)
    at handleResponse (extensions::sendRequest:72)n @ background.js:18
```

**Comment by cpoppema** [comment]
That is the same error I get while testing the scenario's I just posted. This should mean ``pass`` did not initialize with the key from the plugin. Can you try running this again ? ``pass init $key1 $key2 etc..`` with all the keys you want ?

**Comment by x4121** [comment]
Do you mean signing the key or setting the trust? It's set to `trust: ultimate`, I re-initialized the password store (which shouldn't work if one of the keys is not trusted) and there's still the same `TypeError: Cannot read property...`

**Comment by cpoppema** [comment]
I will keep digging for a bit to see if I'm missing something obvious, but can you try signing the key to see if that makes a difference ? You can sign a key with ``gpg --sign-key <keyid>`` on your server, the key will then be signed with one of the keys listed in ``gpg --list-secret-keys``.

**Comment by x4121** [comment]
OK, this is strange. When manually decrypting the gpg files in password storage it says
```
gpg: encrypted with 4096-bit RSA key, ID 0x...
gpg: encrypted with 4096-bit RSA key, ID 0x...
```
But it doesn't list the ID that is used by the extension, only the two previous keys.
Signing the key didn't seem to help either (one of the above listed keys also isn't signed).

**Comment by x4121** [comment]
OK, wow... this seems to be a bug or special "feature" in pass...
I had `PASSWORD_STORE_KEY` set to my two gpg keys, what let to pass ignoring the keys specified with `pass init ...` (even thou these are no optional parameters) but still print the message that it did initialize the storage as described in `pass init ...` and put them in .gpg-id

**Comment by cpoppema** [comment]
Glad you figured it out!

I have not used ``PASSWORD_STORE_KEY`` myself, but what you describe is intended (or at least documented) behavior from what I can tell:

        PASSWORD_STORE_KEY
              Overrides the default gpg key identification set by init. Keys must not 
              contain spaces and thus use of the hexidecimal key signature is recommended.
              Multiple keys may be specified separated by spaces.

Hope you can finally use the plugin now :)

**Comment by x4121** [comment]
Sorry to bother you with this for so long. Plugin works like a charm now (additional autofill would be much appreciated :wink:)

In case of pass, to me this still feels somewhat buggy if it prints "I'm encrypting it for X" but it doesn't.
